### ISSUE TITLE
Change the fucking name

### ISSUE THREAD

**Issue by robphoenix** [gocreating/react-virtual-table#1]
While this uses `fuck` in the name and throughout the package, it is totally unusable in enterprise applications. Which is a shame as it is the only package I have found that uses native table elements instead of divs for a virtual table.

**Comment by gocreating** [comment]
@robphoenix Actually the whole library is just a single file, you can fork or even copy paste to a new name.
As I explained in the [project home page](https://github.com/gocreating/fucking-react-table#why), my preferred name was registered. Any suggestion for a new name?

**Comment by robphoenix** [comment]
I've forked it under the name `rvt` (imaginative eh 😄 ) 

I'm gonna close this, as you can name it what you want really, just thought I'd let you know that to use this at work I'm gonna have to use a renamed fork. Thanks for building it in the first place 👌
